SRC=src/hardw
OUT=out
OBJS=$(OUT)/OBJS
GCC=gcc -c

all:
	mkdir -p  $(OUT)
	mkdir -p  $(OBJS)
	echo "Compiling hardware files..."
	$(GCC) -o $(OBJS)/servoMotor.o $(SRC)/servoMotor.cpp -lwiringPi
	echo "HARDWARE libs compiled OK!!!"
