SRC=src/hardw
OUT=out
OBJS=$(OUT)/OBJS
GCC=gcc -c

all:
	mkdir -p  $(OUT)
	mkdir -p  $(OBJS)
	echo "Compiling hardware files..."
	$(GCC) $(SRC)/deviceStarter.c -o $(OBJS)/hardwLib.o
	echo "HARDWARE libs compiled OK!!!"
