SRC=../../src/
OUT=out
OBJS=$(OUT)/OBJS
GNAT=gnatmake -c

all:
	mkdir -p  $(OUT)
	mkdir -p  $(OBJS)
	echo "Compiling software files..."
	cd $(OBJS); $(GNAT) $(SRC)/devices.adb -o devices.o
	cd $(OBJS); $(GNAT) $(SRC)/main.adb -o main.o
	echo "Linking files..."
	cd $(OBJS); gnatbind main.ali
	cd $(OBJS); gnatlink main.ali servoMotor.o temperature.o pressure.o -lwiringPi
	mv $(OBJS)/main $(OUT)/ARM
	echo "SOFTWARE compiled OK!!!"
